# Generated by Django 5.1.2 on 2025-07-24 07:49

import concurrency.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0047_remove_botevent_valid_event_type_event_sub_type_combinations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='bots.bot'),
        ),
        migrations.CreateModel(
            name='MeetingAppSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('settings', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zoom_rtms_stream_id', models.CharField(blank=True, max_length=255, null=True)),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('state', models.IntegerField(choices=[(1, 'Ready'), (2, 'Connecting'), (3, 'Connected'), (4, 'Post Processing'), (5, 'Ended'), (6, 'Fatal Error')], default=1)),
                ('metadata', models.JSONField(default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_app_sessions', to='bots.project')),
            ],
        ),
        migrations.AddField(
            model_name='recording',
            name='meeting_app_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='bots.meetingappsession'),
        ),
        migrations.CreateModel(
            name='MeetingAppSessionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('old_state', models.IntegerField(choices=[(1, 'Ready'), (2, 'Connecting'), (3, 'Connected'), (4, 'Post Processing'), (5, 'Ended'), (6, 'Fatal Error')])),
                ('new_state', models.IntegerField(choices=[(1, 'Ready'), (2, 'Connecting'), (3, 'Connected'), (4, 'Post Processing'), (5, 'Ended'), (6, 'Fatal Error')])),
                ('event_type', models.IntegerField(choices=[(1, 'Connection Requested'), (2, 'Connection Established'), (3, 'Connection Failed'), (4, 'Connection Ended'), (5, 'Post Processing Completed'), (6, 'Fatal Error')])),
                ('event_sub_type', models.IntegerField(blank=True, choices=[(1, 'Fatal Error Meeting App Session Not Launched'), (2, 'Fatal Error Process Terminated')], null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('requested_meeting_app_session_action_taken_at', models.DateTimeField(blank=True, null=True)),
                ('meeting_app_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='bots.meetingappsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='meetingappsession',
            constraint=models.UniqueConstraint(fields=('zoom_rtms_stream_id',), name='unique_zoom_rtms_stream_id'),
        ),
    ]
