# Generated by Django 5.1.2 on 2025-08-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0051_alter_webhookdeliveryattempt_webhook_trigger_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSession',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bots.bot',),
        ),
        migrations.AddField(
            model_name='bot',
            name='session_type',
            field=models.IntegerField(choices=[(1, 'Bot'), (2, 'App Session')], default=1),
        ),
        migrations.AddField(
            model_name='bot',
            name='zoom_rtms_stream_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
