# Generated by Django 5.1.2 on 2025-08-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0052_alter_webhookdeliveryattempt_webhook_trigger_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSession',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bots.bot',),
        ),
        migrations.CreateModel(
            name='BotSession',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bots.bot',),
        ),
        migrations.AddField(
            model_name='bot',
            name='session_type',
            field=models.IntegerField(choices=[(1, 'Bot'), (2, 'App Session')], default=1),
        ),
        migrations.AddField(
            model_name='bot',
            name='zoom_rtms_stream_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='state',
            field=models.IntegerField(choices=[(1, 'Ready'), (2, 'Joining'), (3, 'Joined - Not Recording'), (4, 'Joined - Recording'), (5, 'Leaving'), (6, 'Post Processing'), (7, 'Fatal Error'), (8, 'Waiting Room'), (9, 'Ended'), (10, 'Data Deleted'), (11, 'Scheduled'), (12, 'Staged'), (13, 'Joined - Recording Paused'), (100, 'Connecting'), (101, 'Connected'), (102, 'Disconnecting')], default=1),
        ),
        migrations.AlterField(
            model_name='botevent',
            name='event_type',
            field=models.IntegerField(choices=[(1, 'Bot Put in Waiting Room'), (2, 'Bot Joined Meeting'), (3, 'Bot Recording Permission Granted'), (4, 'Meeting Ended'), (5, 'Bot Left Meeting'), (6, 'Bot requested to join meeting'), (7, 'Bot Encountered Fatal error'), (8, 'Bot requested to leave meeting'), (9, 'Bot could not join meeting'), (10, 'Post Processing Completed'), (11, 'Data Deleted'), (12, 'Bot staged'), (13, 'Recording Paused'), (14, 'Recording Resumed'), (100, 'App Session Connection Requested'), (101, 'App Session Connected'), (102, 'App Session Disconnect Requested'), (103, 'App Session Disconnected')]),
        ),
        migrations.AlterField(
            model_name='botevent',
            name='new_state',
            field=models.IntegerField(choices=[(1, 'Ready'), (2, 'Joining'), (3, 'Joined - Not Recording'), (4, 'Joined - Recording'), (5, 'Leaving'), (6, 'Post Processing'), (7, 'Fatal Error'), (8, 'Waiting Room'), (9, 'Ended'), (10, 'Data Deleted'), (11, 'Scheduled'), (12, 'Staged'), (13, 'Joined - Recording Paused'), (100, 'Connecting'), (101, 'Connected'), (102, 'Disconnecting')]),
        ),
        migrations.AlterField(
            model_name='botevent',
            name='old_state',
            field=models.IntegerField(choices=[(1, 'Ready'), (2, 'Joining'), (3, 'Joined - Not Recording'), (4, 'Joined - Recording'), (5, 'Leaving'), (6, 'Post Processing'), (7, 'Fatal Error'), (8, 'Waiting Room'), (9, 'Ended'), (10, 'Data Deleted'), (11, 'Scheduled'), (12, 'Staged'), (13, 'Joined - Recording Paused'), (100, 'Connecting'), (101, 'Connected'), (102, 'Disconnecting')]),
        ),
        migrations.AlterField(
            model_name='webhookdeliveryattempt',
            name='webhook_trigger_type',
            field=models.IntegerField(choices=[(1, 'State Change'), (2, 'Transcript Update'), (3, 'Chat Messages Update'), (4, 'Participant Join/Leave'), (5, 'Calendar Events Update'), (6, 'Calendar State Change')], default=1),
        ),
    ]
